export const COMMON_TIMEZONES: ReadonlyArray<{ label: string; value: string }> = [
  { label: 'UTC', value: 'UTC' },
  { label: 'Europe/Madrid (Spain)', value: 'Europe/Madrid' },
  { label: 'Europe/London', value: 'Europe/London' },
  { label: 'Europe/Paris', value: 'Europe/Paris' },
  { label: 'Europe/Berlin', value: 'Europe/Berlin' },
  { label: 'Europe/Rome', value: 'Europe/Rome' },
  { label: 'America/Sao_Paulo (Brazil)', value: 'America/Sao_Paulo' },
  { label: 'America/Argentina/Buenos_Aires', value: 'America/Argentina/Buenos_Aires' },
  { label: 'America/Santiago (Chile)', value: 'America/Santiago' },
  { label: 'America/Bogota (Colombia)', value: 'America/Bogota' },
  { label: 'America/Lima (Peru)', value: 'America/Lima' },
  { label: 'America/Mexico_City', value: 'America/Mexico_City' },
  { label: 'America/New_York', value: 'America/New_York' },
  { label: 'America/Los_Angeles', value: 'America/Los_Angeles' },
  { label: 'Asia/Tokyo', value: 'Asia/Tokyo' },
  { label: 'Asia/Seoul', value: 'Asia/Seoul' },
  { label: 'Asia/Shanghai', value: 'Asia/Shanghai' },
  { label: 'Asia/Manila (Philippines)', value: 'Asia/Manila' },
  { label: 'Australia/Sydney', value: 'Australia/Sydney' },
];
